Fixed use of "window" instead of "global".
dignifiedquire/webcrypto-shim pull request #1
Opened 2017-01-14 12:46 UTC by tswindell

Signed-off-by: Tom Swindell <t.swindell@rubyx.co.uk>

2017-01-14 12:49 UTC, dignifiedquire requested changes

2017-01-14 12:49 UTC, dignifiedquire commented on webcrypto-shim.js
> +    var isEdge = global.navigator.userAgent.indexOf('Edge/') > -1
I don't think global is defined in all browsers, maybe check for not begin undefined in this order

1. global
2. window
3. self

2017-01-14 17:06 UTC, tswindell commented on webcrypto-shim.js
> +    var isEdge = global.navigator.userAgent.indexOf('Edge/') > -1
global is a local variable, it is the variable that is assigned to window or self.

2017-01-14 19:52 UTC, dignifiedquire commented on webcrypto-shim.js
> +    var isEdge = global.navigator.userAgent.indexOf('Edge/') > -1
I should read the code I'm reviewing more closely :/

2017-01-14 19:52 UTC, dignifiedquire commented
Thank you :octocat:

2017-01-14 19:52 UTC, dignifiedquire approved these changes

2017-01-14 19:52 UTC, merged

2017-02-01 17:03 UTC, tswindell commented
Is this closed now then? ;)

2017-02-01 17:09 UTC, dignifiedquire commented
latest libp2p-crypto includes this and runs tests in webworkers so should work all good now :)